### ISSUE TITLE
Unable to MVN Install version 1.5.4

### ISSUE THREAD

**Issue by conv317** [PayPal-Mobile/android-here-sdk-dist#17]
Hi, 

There seems to be a issue with using Maven on the latest release 1.5.4 to compile the aar. 
Version 1.5.3 works using the same method without any issues. 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install-file (defau
lt-cli) on project standalone-pom: The specified file 'C:\Users\covafeas\Documents\Development\sdks\
android-here-sdk-dist-master1.5.4\android-here-sdk-dist-master\sdk\PayPalHereSDK-1.5.4-debug.aar' not exists -> [Help 1]
[ERROR]

Thanks,

**Comment by ppmtscory** [comment]
@conv317 Can you please double-check your file path to the .aar file?  I was able to reproduce the error only when I input the incorrect file path or .aar file name.  Otherwise, it compiles just fine for me.
