### ISSUE TITLE
Can't Login into Sample App

### ISSUE THREAD

**Issue by VictorDL** [PayPal-Mobile/android-here-sdk-dist#28]
I have built the SampleApp in Android Studio but I can't login using any credentials. I have used the teashop userid and password, my Sandbox Account, and my Live ID. Each time I get a login failed. With this output in the logcat and I have not touched the code yet.  

07-09 14:13:52.593    5022-6600/com.paypal.sampleapp D/PayPalHere.OAuthLoginScreen﹕ Login Response: {"ticket":null}
07-09 14:13:52.593    5022-6600/com.paypal.sampleapp E/PayPalHere.OAuthLoginScreen﹕ No value for merchant
07-09 14:13:52.609    5022-5022/com.paypal.sampleapp D/PayPalHere.OAuthLoginScreen﹕ doneWithLoginPayPal. Login Failed

I have tried on a Samsung Galaxy Tab, sm t210r, and the Motorola  Nexus 6
![screenshot_2015-07-09-14-13-41 1](https://cloud.githubusercontent.com/assets/13260658/8604689/c0d86464-2645-11e5-98e6-286c2d9f505a.png)

![screenshot_2015-07-09-14-22-47 2](https://cloud.githubusercontent.com/assets/13260658/8604736/15c3b4ce-2646-11e5-8aff-6cc9d7feef45.png)

**Comment by ppmtscory** [comment]
Thank you for the screen shots.  It's strange that the 'teashop' username doesn't work here.  Either way, I created a user for you so you should be able to login on this page with 'victordl' (same user as your Github ID).  The password is the same as what I previously provided you for the 'teashop' user.  Once you login with that username/password, then you should be prompted to login with your sandbox merchant account.

**Comment by VictorDL** [comment]
Thank You for your help I'm in!

**Comment by ppmtscory** [comment]
No problem.  I'll close this issue out but feel free to open another issue if you have any further problems.
