### ISSUE TITLE
DexIndexOverflowException

### ISSUE THREAD

**Issue by valdvir** [PayPal-Mobile/android-here-sdk-dist#29]
When compiling with the AAR file, we get *lots* of warning these style:
```
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.paypal.merchant.sdk.internal.service.cal.j) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
```

And at the end of the compilation process the following error:
```
com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
```

Basically, it doesn't compile.

**Comment by lernerb** [comment]
Hey @valdvir, does your app extend either `Application` or `MultiDexApplication` in your class referenced from `AndroidManifest.xml`?
 
It looks like your application has too many methods. You can only use up to 65536 methods in an application that doesn't use the MultiDexApplication API.

Take a look at this to resolve your issue: https://developer.android.com/tools/building/multidex.html

I'll take a look into the compiler warnings and report back.

**Comment by valdvir** [comment]
`MultiDexApplication` solved it. Thanks!
