### ISSUE TITLE
Google Play Services incompatibility

### ISSUE THREAD

**Issue by ryazmin** [PayPal-Mobile/android-here-sdk-dist#36]
Fatal Exception: java.lang.IncompatibleClassChangeError: The method 'boolean com.google.android.gms.common.api.GoogleApiClient.isConnected()' was expected to be of type interface but instead was found to be of type virtual (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)
       at com.paypal.merchant.sdk.internal.service.GooglePlayLocationServiceImpl.startLocationService(GooglePlayLocationServiceImpl.java:48)
       at com.paypal.merchant.sdk.internal.SDKCore.init(SDKCore.java:166)
       at com.paypal.merchant.sdk.PayPalHereSDK.init(PayPalHereSDK.java:163)

**Comment by ryazmin** [comment]
https://www.reddit.com/r/androiddev/comments/3mehbb/breaking_changes_in_google_play_services_81/

**Comment by lernerb** [comment]
Hi Roman,

Can you let us know some debug information to fix this issue.

* What version of PayPal Here are you using from the play store?
* What phone are you running this on?

Thanks for the stack trace and bringing up this issue!

**Comment by ryazmin** [comment]
Using PayPalHereSDK-1.6.1-release
and the app is using  play-services-location version 8.1.0

The article from the reddit completely describes the issue.
Looks like PayPalHereSDK-1.6.1 is compiled agains pre-8.1.0 version of Google Play Services,
so if the app uses 8.1.0 or higher version then the crash happens.

Here is from release notes for 8.1
GoogleApiClient, PendingResult, and OptionalPendingResult are now abstract classes instead of interfaces.

**Comment by lernerb** [comment]
Got it, thanks. Will bring this up to the team w/ the docs for a fix.

**Comment by hamidsani** [comment]
I also ran into this issue and was hoping for a solution. Good to know that you guys are working on it.

**Comment by rakesh-ideal** [comment]
Hi lernerb,  Any updates about Google Play Services incompatibility issue ? i also waiting for this fix.

**Comment by balage-amarasena** [comment]
Hi lernerb, 
We are also having the same issue. we are using the PayPalHereSDK-1.6.1.1-release.aar with play-services-location:8.4.0. Can you please let us know if there is a fix or workaround for this ?

**Comment by PaulNeesham** [comment]
Just wondering if there is an ETA for when this will be fixed. Version 8 came out almost a year ago (September 2015) and not supporting it is holding us back from using any features and bug fixes added to play services. I would also argue this is a bug not an enhancement due to the fact it is stopping play service bugs being fixed in the apps paypal is bundled with.

**Comment by ppmtscory** [comment]
Hey All - I'm checking with the team on where this lies in the backlog of work.  Once I have any updates, I will be sure to let you know.

**Comment by karthikrajan22** [comment]
Hi Every One,
   Am using
   **PayPalHereSDK-1.6.1-release**
  **and the app is using firebase-messaging and play-services-location version 9.0.0** for module gradle. when am using this to compile i got this error messages **The method 'boolean com.google.android.gms.common.api.GoogleApiClient.isConnected()' was expected to be of type interface but instead was found to be of type virtual (declaration of 'com.paypal.merchant.sdk.internal.service.GooglePlayLocationServiceImpl' appears in /data/app/com.njride.driver-2/base.apk)** .

**Note:** Am using the FCM Notification, PayPalHereSDK-1.6.1-release and Google Play Services for Map, location and gcm.

Kindly Help me this issues. Thanks in an advance..!

**Comment by ppmtscory** [comment]
All - my apologies on the delay but this was updated and is available with the latest release in the repo.

**Comment by karthikrajan22** [comment]
@ppmtscory  Got it man.. Thanks.. Worked.!
