### ISSUE TITLE
Paypal Here Merchant Account

### ISSUE THREAD

**Issue by abhirav** [PayPal-Mobile/android-here-sdk-dist#38]
Few months back when I was integrating Paypal Here SDK (Android) I was required to use US merchant account. I am in Australia. Do Paypal Here SDK now support Australian Merchant Account?

**Comment by developersteve** [comment]
@abhirav yep we have supported Australian merch accounts using the SDK for while, just sign up at https://apply.paypal-apac.com/here/au/Step1A.aspx and you'll go through the approval process. 

Let me know if you have any issues
