### ISSUE TITLE
EMV screen

### ISSUE THREAD

**Issue by hamidsani** [PayPal-Mobile/android-here-sdk-dist#41]
I'm developing a kiosk app where the EMV will be attached to the side of the kiosk and unattented so the customer could just walk up, order, and pay. The issue that I'm having is that the EMV screen stays on and the only way I could reset it is through disconnecting from the EMV and reconnect it later. Is there anywhere around this issue? Any method that I could tell the EMV that the order is done and go to sleep?

Thanks in advance

**Comment by djMax** [comment]
You should be able to disconnect from the reader and it will go to sleep something like 60 seconds later. But, you would then need to press a button on it to wake it back up again. If the device is attached, will it be powered? If so then not sure you need to bother putting it to sleep.

**Comment by hamidsani** [comment]
huh... I guess I could disconnect and reconnect it quickly before it time outs. And yeah, the EMV would be plugged into power. This sounds a bit strange but I had the card reader fully integrated in my app and it worked for two months but suddenly starting a week ago pretty much all three different card readers that I have don't read any card swipe. Even the paypal here app recognized the readers but doesn't register a swipe. Even calling the customer support didn't help. So here I am trying to get the EMV working.

**Comment by hamidsani** [comment]
I'll let you know if disconnecting and reconnecting back to the EMV reader quickly does the trick. Thanks for the tip.

**Comment by hamidsani** [comment]
Yeah, I was able to disconnect from the EMV reader and reconnect quickly to refresh the screen. I also bought a right angle usb connector to keep the EMV reader fully charge. The usb location makes it really awkward to have it charging and people to swipe the card.
