### ISSUE TITLE
Problem communicating with the paypal servers

### ISSUE THREAD

**Issue by pjojeda** [PayPal-Mobile/android-here-sdk-dist#45]
I'm getting this error on the screen checking this device, I'm using a sony xperia ZL with android 4.4.4, and I tested it in a nexus 7 with the same version of android as well. 

![screenshot_2016-01-29-10-17-59](https://cloud.githubusercontent.com/assets/4325248/12676840/c7db888a-c673-11e5-9663-ea2f5950963d.png)

the log shows this error

E/paypal.sdk: request failed with server response:null
E/paypal.sdk: SERVER_COMMUNICATION_ERROR

The thing is, testing it on a samsung with android 5.1 it works perfect.

**Comment by ppmtscory** [comment]
@pjojeda first things first, you are using the PayPal mSDK and not the PPH SDK.  Therefore, while I will attempt to answer your questions, if you have further issues, you'll need to report them [here](https://github.com/paypal/PayPal-Android-SDK/issues).

To answer your question, this very well could have something to do with the latest updates to Sandbox to support only TLSv1.2.  More information can be found [here](https://github.com/paypal/TLS-update) under Native Mobile Apps.  If, after reviewing that page and checking your app, you still have issue, feel free to open an issue in the Android SDK repo that I linked to above.
