### ISSUE TITLE
Mobile Credit Card Reader/Swiper not detecting in android phone.

### ISSUE THREAD

**Issue by rakesh-ideal** [PayPal-Mobile/android-here-sdk-dist#49]
Just install "HereSDKSampleApp.apk" file (provided with android-here-sdk-dist-master)  
Tried in Sandbox mode and get Login successfully,
Shows three options to make Payment,  
Chose "PAYMENT USING AUDIO JACK READER",
Always showing "Please plug-in audio jack reader" message,  
I have connected Audio Jack Reader with phone.
 Device specification:
 Samsung J5
 Android v 5.1.1

**Comment by ppmtscory** [comment]
Even though it still shows the plug in message, does it recognize a swiped card?

**Comment by rakesh-ideal** [comment]
No, its not recognizing a swiped card,  still showing message.

**Comment by ppmtscory** [comment]
Ah, my apologies for not reading the issue thoroughly before, but if your account isn't set up for PayPal Here, then the SDK won't be able to initialize the merchant and therefore won't continue to detect the reader.  When creating a sandbox account, if you create a US Business account with the first name of Ryan, then you should be able to get it signed up for PayPal Here and then use it within the sample App.  Pages 5-9 of the onboarding guide in the Docs folder of this repo explains how to set up the onboarding to get a merchant signed up for PayPal Here.  When submitting the form to login to, simply change the URL from www.paypal.com to www.sandbox.paypal.com.  Then you'll click to login with the account you created and the response to your return URL should be a success.

**Comment by rakesh-ideal** [comment]
We created new account as described in Docs, Now its complete flow is working, Thanks.
But, I don't want to user should login into the paypal to swipe card, i want to avoid login process to generate access token then,
How we can generate "compositeAccessToken" using Client ID and Secret ?

**Comment by ppmtscory** [comment]
@rakesh-ideal the merchant should only have to login the single time as then you would save the refresh token for later use.  The merchant will login, apply for PayPal Here (if necessary), and then provide the permissions to your account.  You'll notice that there's a refresh token returned with the access token.  You need to store this refresh token for this merchant.  When you need to generate a new access token, you'll simply use this refresh token to do so.

The composite access tokens are generated by the Sample Server which is located [here](https://github.com/paypal/paypal-retail-node) so you can use that or you can set your own server and set up the merchant with the access token directly.

**Comment by rakesh-ideal** [comment]
OK i got it, i can store refresh token for further use and avoid login process, but now i want to same for iOS app so i just used PayPal-Mobile/ios-here-sdk-dict, Everything is working fine, but generated token does not seems to refresh token its expiring in 8 hour, so
How i can generate refresh token for iOS app as generating in android sample ?  
I checked android app generated refresh token not working with iOS app ?

**Comment by ppmtscory** [comment]
Closing as this auto-refreshing issue is being handled in the iOS repo.

**Comment by stefansidler1993** [comment]
if your phone does not recognize your card reader remember to allow all the permission to the app like location and microphone

**Comment by stefansidler1993** [comment]
if your phone does not recognize your card reader remember to allow all the permission to the app like location and microphone
