### ISSUE TITLE
Stopping the receipt dialogue from appearing.

### ISSUE THREAD

**Issue by JamesRoche** [PayPal-Mobile/android-here-sdk-dist#51]
Hi,

I am having trouble locating an API to stop the receipt window from showing. My app and web service will send receipts as part of an order which is raised during payment so it will be confusing for our cashiers having to click no recipes after every payment. We obviously want to brand our own receipts via email and SMS which our platform already does. I notice there is a ReceiptOptions in the  TransAction controller but its not clear how to implement this.

@Override
        public SDKReceiptScreenOptions getReceiptScreenOptions() {
            return null;
        }

Can you assist?

**Comment by djMax** [comment]
Not sure if you're doing EMV or swipe, but for EMV this is a certification requirement because our receipts are "special" in that they meet EMV certification criteria and thus we can't remove that from the overall flow.

**Comment by JamesRoche** [comment]
We just do chip and pin and contactless. Is there an option to remove this?

**Comment by ppmtscory** [comment]
@JamesRoche there is no way to remove the receipt screens from the SDK UI due to them being there to please EMV requirements.

**Comment by JamesRoche** [comment]
Ok thanks, what is the function of receipt options method i mentioned earlier?

**Comment by ppmtscory** [comment]
According to the Javadocs, `This function gets called when ever the SDK is about to show the Receipt options screen.`
