### ISSUE TITLE
Updating failed

### ISSUE THREAD

**Issue by mariannegru** [PayPal-Mobile/android-here-sdk-dist#52]
Hi,

Using sample app and a PayPal chip card reader I get an update fail error:

First error in logs is:

`03-25 21:41:32.221 15613-15709/com.paypal.heresdk.sampleapp E/Volley: [18169] BasicNetwork.performRequest: Unexpected response code 500 for https://www.sandbox.paypal.com/webapps/hereapi/merchant/v1/cardReaderDevice/MIURA/M000/keys
03-25 21:41:32.221 15613-15613/com.paypal.heresdk.sampleapp E/PPHSDK: HereDeviceKeysRequest- RESPONSE BODY ON ERROR: {"correlationId":"248d5cd610ca","errorCode":600000,"message":"MobileMerchantPaymentServ: Unknown Error Code: 506713","errorType":"service_error"}
03-25 21:41:32.221 15613-15613/com.paypal.heresdk.sampleapp D/PPHSDK: PPHSDK.MerchantManagerImpl-Active merchant is present.
03-25 21:41:32.221 15613-15613/com.paypal.heresdk.sampleapp D/PPHSDK: CalLoggingService-NEW MESSAGE: {"status":"-1","type":"BIZ","name":"Message.CLIENT","data":{"sessionId":"78c02665-9016-4139-869c-dc0d875cd46a","timestamp":"2016-03-25 19:41:32:236 +0000","actionId":"Message","level":"ERROR","result":"-1","details":"marian-facilitator@icabbi.com : :  RESPONSE BODY ON ERROR: {\"correlationId\":\"248d5cd610ca\",\"errorCode\":600000,\"message\":\"MobileMerchantPaymentServ: Unknown Error Code: 506713\",\"errorType\":\"service_error\"}"}}
03-25 21:41:32.241 15613-15613/com.paypal.heresdk.sampleapp E/PPHSDK: HereDeviceKeysRequest-Failure response from backend and contains errors. ErrorCode: 600000`

After that I get an exception:

`03-25 21:41:32.361 15613-15613/com.paypal.heresdk.sampleapp D/PPHSDK: PPHSDK+MiuraM10DisplayFormatter-String to format : Software update
                                                                      failed. 
                                                                       with alignment : CENTER
03-25 21:41:32.361 15613-15613/com.paypal.heresdk.sampleapp D/PPHSDK: PPHSDK+MiuraM10DisplayFormatter-Formatted String :    Software update  
                                                                             failed.      
03-25 21:41:32.361 15613-15613/com.paypal.heresdk.sampleapp D/PPHSDK: PPHSDK+MiuraM10DisplayFormatter-Applying padding to string :    Software update  
                                                                             failed.      
03-25 21:41:32.361 15613-15613/com.paypal.heresdk.sampleapp D/PPHSDK: PPHSDK+MiuraM10DisplayFormatter-Formatted String : 
                                                                         Software update  
                                                                             failed.      
03-25 21:41:32.361 15613-15613/com.paypal.heresdk.sampleapp V/PPHSDK: CardReaderManagerImpl-isReaderConnected IN
03-25 21:41:32.361 15613-15613/com.paypal.heresdk.sampleapp D/PPHSDK: CreditCardReaders-getActiveReaderType
03-25 21:41:32.361 15613-15613/com.paypal.heresdk.sampleapp V/PPHSDK: CardReaderManagerImpl-displayTextOnTerminal Text: 
                                                                         Software update  
                                                                             failed.       displaySystemIcons: true
03-25 21:41:32.361 15613-15613/com.paypal.heresdk.sampleapp V/PPHSDK: BOND LIB-displayTextOnTerminalScreen.....
03-25 21:41:32.361 15613-15613/com.paypal.heresdk.sampleapp V/PPHSDK: BOND LIB-Message To Terminal: 01002FD20101002A0A202020536F6674776172652075706461746520200A202020202020206661696C65642E202020202020E5
03-25 21:41:32.391 15613-15680/com.paypal.heresdk.sampleapp D/mali_winsys: new_window_surface returns 0x3000,  [1592x1768]-format:1
03-25 21:41:32.401 15613-15613/com.paypal.heresdk.sampleapp W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
03-25 21:41:32.411 15613-22952/com.paypal.heresdk.sampleapp V/PPHSDK: BOND LIB-Message From Terminal: 01000EE10ADFA2090100DFA20A015890002F
03-25 21:41:32.411 15613-22952/com.paypal.heresdk.sampleapp W/System.err: java.lang.ArrayIndexOutOfBoundsException: src.length=12 srcPos=0 dst.length=1440 dstPos=1440 length=12
03-25 21:41:32.411 15613-22952/com.paypal.heresdk.sampleapp W/System.err:     at java.lang.System.arraycopy(Native Method)
03-25 21:41:32.411 15613-22952/com.paypal.heresdk.sampleapp W/System.err:     at com.paypal.merchant.sdk.readers.chipnpin.MiuraSupport.Bond.readP2PEFileResponseReceived(Bond.java:717)
03-25 21:41:32.411 15613-22952/com.paypal.heresdk.sampleapp W/System.err:     at com.paypal.merchant.sdk.readers.chipnpin.MiuraSupport.Bond.parseResponse(Bond.java:1704)
03-25 21:41:32.411 15613-22952/com.paypal.heresdk.sampleapp W/System.err:     at com.paypal.merchant.sdk.readers.chipnpin.MiuraSupport.BluetoothServiceListenerImpl.responseReceived(BluetoothServiceListenerImpl.java:49)
03-25 21:41:32.411 15613-22952/com.paypal.heresdk.sampleapp W/System.err:     at com.paypal.merchant.sdk.readers.chipnpin.MiuraSupport.BluetoothService$ConnectedThread.run(BluetoothService.java:420)`

How can I solve this issue?

Thank you

**Comment by ppmtscory** [comment]
@mariannegru your logs show that you are using the sandbox environment.  The chip readers are not able to run in the sandbox environment due to complications with EMV processing.  You'll need to use Production with the Sample App if you are using a Chip reader.

**Comment by mariannegru** [comment]
So I need to have a merchant production account to develop and test an application?

**Comment by ppmtscory** [comment]
Correct.  Currently, in order to test payments, you would need to use a Production account.  You can test the onboarding and manual entry processing in the Sandbox, but any software updates or swipe, insert, or tap payments have to be in Production.  You would simply refund your test payments back to your card from your merchant account.

**Comment by karthikrajan22** [comment]
Hi Cory,
Am using Paypal Chip Card Reader, when am proceed the transcation, at the end the "Transcation Cancelled Message" is showing in both Mobile and Paypal Chip Card Reader.
I have posted the request and reponse information with this.

_> Unexpected response code 500 for https://www.paypal.com/webapps/hereapi/merchant/v1/payment//void

    10-26 08:21:50.767 31119-31119/com.paypal.heresdk.sampleapp E/PPHSDK: HereFinalizePaymentRequest- RESPONSE BODY ON ERROR: {"correlationId":"944934e96fea4","errorCode":600000,"message":"Unrecognized field \"emvData\" (Class com.paypal.hereapi.rest.merchant.model.payment.PaymentRequest), not marked as ignorable\n at Source: org.apache.catalina.connector.CoyoteInputStream@1fffb6b; line: 1, column: 52","errorType":"service_error"}_

Thank you ..!

**Comment by ppmtscory** [comment]
Your error is different than this issue that was closed long ago.  Please open a new issue with what you're seeing.
