### ISSUE TITLE
Sample Server incompatibility

### ISSUE THREAD

**Issue by mariannegru** [PayPal-Mobile/android-here-sdk-dist#53]
Hi,

Server sample is not used with the sample android app. Starting server and setting the url in LoginActivity.java would not work.

Where is the app sample working with the sample server, or where can I find app working with the server.

My problem is that I've implemented the goApp into my server like is implemented into sample_server/heroku_server/server.js goApp but I get the error:

`03-26 22:32:47.871 20911-20911/com.paypal.heresdk.sampleapp W/System.err: java.util.NoSuchElementException
03-26 22:32:47.881 20911-20911/com.paypal.heresdk.sampleapp W/System.err:     at java.util.StringTokenizer.nextToken(StringTokenizer.java:208)
03-26 22:32:47.881 20911-20911/com.paypal.heresdk.sampleapp W/System.err:     at com.paypal.merchant.sdk.internal.SDKCore.setCredentialsFromCompositeStrFromMidtierServer(SDKCore.java:448)
03-26 22:32:47.881 20911-20911/com.paypal.heresdk.sampleapp W/System.err:     at com.paypal.merchant.sdk.PayPalHereSDK.setCredentialsFromCompositeStrFromMidTierServer(PayPalHereSDK.java:215)
03-26 22:32:47.881 20911-20911/com.paypal.heresdk.sampleapp W/System.err:     at com.paypal.heresdk.sampleapp.sdk.PayPalHereSDKWrapper.setAccessTokenToSDK(PayPalHereSDKWrapper.java:79)
03-26 22:32:47.881 20911-20911/com.paypal.heresdk.sampleapp W/System.err:     at com.paypal.heresdk.sampleapp.sdk.PayPalHereSDKWrapper.initializeSDK(PayPalHereSDKWrapper.java:69)
03-26 22:32:47.881 20911-20911/com.paypal.heresdk.sampleapp W/System.err:     at com.paypal.heresdk.sampleapp.login.LoginActivity.startPaymentOptionsActivity(LoginActivity.java:159)
03-26 22:32:47.881 20911-20911/com.paypal.heresdk.sampleapp W/System.err:     at com.paypal.heresdk.sampleapp.login.LoginActivity.access$100(LoginActivity.java:29)
03-26 22:32:47.881 20911-20911/com.paypal.heresdk.sampleapp W/System.err:     at com.paypal.heresdk.sampleapp.login.LoginActivity$1.shouldOverrideUrlLoading(LoginActivity.java:115)
03-26 22:32:47.881 20911-20911/com.paypal.heresdk.sampleapp W/System.err:     at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:336)
03-26 22:32:47.881 20911-20911/com.paypal.heresdk.sampleapp W/System.err:     at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:168)
03-26 22:32:47.881 20911-20911/com.paypal.heresdk.sampleapp W/System.err:     at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:265)
03-26 22:32:47.881 20911-20911/com.paypal.heresdk.sampleapp W/System.err:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
03-26 22:32:47.881 20911-20911/com.paypal.heresdk.sampleapp W/System.err:     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
03-26 22:32:47.881 20911-20911/com.paypal.heresdk.sampleapp W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-26 22:32:47.881 20911-20911/com.paypal.heresdk.sampleapp W/System.err:     at android.os.Looper.loop(Looper.java:158)
03-26 22:32:47.881 20911-20911/com.paypal.heresdk.sampleapp W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7224)
03-26 22:32:47.881 20911-20911/com.paypal.heresdk.sampleapp W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-26 22:32:47.881 20911-20911/com.paypal.heresdk.sampleapp W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
03-26 22:32:47.881 20911-20911/com.paypal.heresdk.sampleapp W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

At least can you tell me how to format the compositeAccessToken that needs to be sent to setCredentialsFromCompositeStrFromMidtierServer, I can not find any documentation?

Thank you

**Comment by ppmtscory** [comment]
The sample server being used is linked underneath the Authentication section of the README and is located [here](https://github.com/paypal/paypal-retail-node).  I'll see about either making a note in the sample server directory or removing that directory altogether.
