### ISSUE TITLE
Close receipt screen form custom SDKReceiptScreenOptions

### ISSUE THREAD

**Issue by mariannegru** [PayPal-Mobile/android-here-sdk-dist#58]
Hi,

How can I close the receipt screen on a custom receipt? If I finish the activity I'll not get the transaction failure or success.

Best regards,
Marian

**Comment by ppmtscory** [comment]
@mariannegru this should all be handled within the UI of the SDK when you are using the EMV reader, however I'll keep this issue open while we work through your account setup so that you can run some tests and see if you have any further questions.

**Comment by ppmtscory** [comment]
Closing per external conversation.
