### ISSUE TITLE
Update screen stuck

### ISSUE THREAD

**Issue by mariannegru** [PayPal-Mobile/android-here-sdk-dist#59]
Hi,

Here is the log:

`04-05 14:35:29.861 1531-1713/xxx E/Volley: [5808] BasicNetwork.performRequest: Unexpected response code 400 for https://www.paypal.com/webapps/hereapi/merchant/v1/cardReaderDevice/miura/M010?country=IE&environment=production
04-05 14:35:30.811 1531-2659/xxx V/TerminalMessageTemplate Class: TerminalMessageTemplate len: 10
04-05 14:35:30.891 1531-2659/xxx V/TerminalMessageTemplate Class: TerminalMessageTemplate len: 5
04-05 14:35:31.021 1531-2659/xxx V/TerminalMessageTemplate Class: TerminalMessageTemplate len: 5
04-05 14:35:54.221 1531-1714/xxx I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-05 14:35:54.221 1531-1714/xxx I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-05 14:35:54.671 1531-1714/xxx I/qtaguid: Tagging socket 53 with tag 2972d4bd00000000{695391421,0} uid -1, pid: 1531, getuid(): 10296
04-05 14:35:54.871 1531-1714/xxx I/qtaguid: Tagging socket 150 with tag 2972d4bd00000000{695391421,0} uid -1, pid: 1531, getuid(): 10296
04-05 14:35:55.571 1531-1714/xxx I/qtaguid: Untagging socket 53
04-05 14:36:11.211 1531-2659/xxx V/TerminalMessageTemplate Class: TerminalMessageTemplate len: 43
04-05 14:36:24.211 1531-1715/xxx I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-05 14:36:24.211 1531-1715/xxx I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-05 14:36:24.211 1531-1715/xxx I/qtaguid: Tagging socket 53 with tag 2972d4bd00000000{695391421,0} uid -1, pid: 1531, getuid(): 10296
04-05 14:36:25.921 1531-1715/xxx I/qtaguid: Untagging socket 53
04-05 14:36:47.621 1531-2659/xxx W/System.err: java.lang.ArrayIndexOutOfBoundsException: src.length=45 srcPos=0 dst.length=27 dstPos=0 length=45
04-05 14:36:47.621 1531-2659/xxx W/System.err:     at java.lang.System.arraycopy(Native Method)
04-05 14:36:47.621 1531-2659/xxx W/System.err:     at com.paypal.merchant.sdk.readers.chipnpin.MiuraSupport.Bond.readP2PEFileResponseReceived(Bond.java:717)
04-05 14:36:47.621 1531-2659/xxx W/System.err:     at com.paypal.merchant.sdk.readers.chipnpin.MiuraSupport.Bond.parseResponse(Bond.java:1704)
04-05 14:36:47.621 1531-2659/xxx W/System.err:     at com.paypal.merchant.sdk.readers.chipnpin.MiuraSupport.BluetoothServiceListenerImpl.responseReceived(BluetoothServiceListenerImpl.java:49)
04-05 14:36:47.621 1531-2659/xxx W/System.err:     at com.paypal.merchant.sdk.readers.chipnpin.MiuraSupport.BluetoothService$ConnectedThread.run(BluetoothService.java:420)
04-05 14:36:47.631 1531-2659/xxx V/TerminalMessageTemplate Class: TerminalMessageTemplate len: 75
04-05 14:36:47.631 1531-2659/xxx W/System.err: java.lang.ArrayIndexOutOfBoundsException: src.length=27 srcPos=2 dst.length=75 dstPos=0 length=75
04-05 14:36:47.631 1531-2659/xxx W/System.err:     at java.lang.System.arraycopy(Native Method)
04-05 14:36:47.631 1531-2659/xxx W/System.err:     at com.paypal.merchant.sdk.readers.chipnpin.MiuraSupport.TerminalMessageTemplate.parse(TerminalMessageTemplate.java:92)
04-05 14:36:47.631 1531-2659/xxx W/System.err:     at com.paypal.merchant.sdk.readers.chipnpin.MiuraSupport.TerminalMessageTemplate.parse(TerminalMessageTemplate.java:54)
04-05 14:36:47.631 1531-2659/xxx W/System.err:     at com.paypal.merchant.sdk.readers.chipnpin.MiuraSupport.Bond.parseResponse(Bond.java:1708)
04-05 14:36:47.631 1531-2659/xxx W/System.err:     at com.paypal.merchant.sdk.readers.chipnpin.MiuraSupport.BluetoothServiceListenerImpl.responseReceived(BluetoothServiceListenerImpl.java:49)
04-05 14:36:47.631 1531-2659/xxx W/System.err:     at com.paypal.merchant.sdk.readers.chipnpin.MiuraSupport.BluetoothService$ConnectedThread.run(BluetoothService.java:420)
04-05 14:36:48.151 1531-2659/xxx V/TerminalMessageTemplate Class: TerminalMessageTemplate len: 5`

**Comment by ppmtscory** [comment]
@mariannegru I'll keep this issue open while we work through your account setup via email and you are able to test out a payment.

**Comment by ppmtscory** [comment]
Closing per external conversation.
