### ISSUE TITLE
Receipt screen locked to landscape orientation

### ISSUE THREAD

**Issue by jarred-s** [PayPal-Mobile/android-here-sdk-dist#62]
We are using the paypal here reader in a kiosk application where it is connected to a tablet.

The tablet is mounted in a portrait orientation and all SDK screens appear correctly except for the final receipt screen that is locked to the landscape orientation.

This is the case when we use the SDK both within our application the included sample app. Orientation is correct when running on a phone (Nexus 6, Note 4) but not the tablet (Pendo Pad 7).

Is there a resource value to override to force landscape for the receipt screen? The portrait_only value has no affect on this screen.

*edit*
Have confirmed this is also a problem on a Nexus 7 tablet.

**Comment by ppmtscory** [comment]
Thank you, @jarred-s.  We'll take a look and get back to you.

**Comment by ppmtscory** [comment]
@jarred-s I'm able to reproduce this so I'll file the issue with the team to allow the appropriate orientation and I'll update you here when the work is completed.

**Comment by jarred-s** [comment]
@ppmtscory Cheers Cory, looking forward to getting a fix.

**Comment by jarred-s** [comment]
As our product is nearing release is there a workaround for this, is it possible to either:

- Disable the receipt screen entirely (force a no-receipt)?
- Modify and repackag the SDK myself, is there anything stopping me from doing this?

**Comment by ppmtscory** [comment]
@jarred-s you won't be able to modify the receipt screen, no, as that is all part of EMV certification requirements.  I'm double checking with the team on an ETA for the fix.

**Comment by ppmtscory** [comment]
This will be fixed with the next release of the SDK which is estimated to happen in the next day or two.

**Comment by ppmtscory** [comment]
Closing as this should be resolved now.
