### ISSUE TITLE
Error updating the EMV chip card reader

### ISSUE THREAD

**Issue by aleksandar9** [PayPal-Mobile/android-here-sdk-dist#63]
I get an error when trying to update the EMV chip card reader. This is what the AS log says:
`[3098] BasicNetwork.performRequest: Unexpected response code 500 for https://www.sandbox.paypal.com/webapps/hereapi/merchant/v1/cardReaderDevice/MIURA/M000/keys`
`HereDeviceKeysRequest- RESPONSE BODY ON ERROR: {"correlationId":"5a6774975de10","errorCode":600000,"message":"MobileMerchantPaymentServ: Unknown Error Code: 506713","errorType":"service_error"}`
I've already tried system restore and total factory reset, but nothing helps.

**Comment by ppmtscory** [comment]
It appears that you are trying to use the EMV reader in the Sandbox environment.  The functions of the EMV reader are only available in the Live/Production environment.

**Comment by aleksandar9** [comment]
I am not a US/UK based developer, regardless I was provided with an EMV
reader by a client. How can I test anything until the live/production
environment is set up?

**Comment by ppmtscory** [comment]
You can test key-in transactions via the Sandbox environment but that does not utilize the EMV reader.  You can, however, still set up the SDK and start the integration - just use keyed transactions for the payment type.  The onboarding also works in the sandbox.

**Comment by karthikrajan22** [comment]
Hi Cory, 
  Am using Paypal Chip Card Reader, when am proceed the transcation, at the end the **"Transcation Cancelled Message"** is showing in both Mobile and Paypal Chip Card Reader. 
I have posted the request and reponse information with this.

_> Unexpected response code 500 for https://www.paypal.com/webapps/hereapi/merchant/v1/payment//void
> 10-26 08:21:50.767 31119-31119/com.paypal.heresdk.sampleapp E/PPHSDK: HereFinalizePaymentRequest- RESPONSE BODY ON ERROR: {"correlationId":"944934e96fea4","errorCode":600000,"message":"Unrecognized field \"emvData\" (Class com.paypal.hereapi.rest.merchant.model.payment.PaymentRequest), not marked as ignorable\n at [Source: org.apache.catalina.connector.CoyoteInputStream@1fffb6b2; line: 1, column: 52] (through reference chain: com.paypal.hereapi.rest.merchant.model.payment.PaymentRequest[\"emvData\"])","errorType":"service_error"}_

Thank you ..!

**Comment by ppmtscory** [comment]
Your error is different than this issue that was closed long ago.  Please open a new issue with what you're seeing.
