### ISSUE TITLE
Updating Card Reader with two different connectToDevice methods FAILED

### ISSUE THREAD

**Issue by mastahnish** [PayPal-Mobile/android-here-sdk-dist#68]
Hello I'm using Here SDK Sample App for Android to get familiar with Card Reader usage flow.

I'm from Poland.
I'm using Sandbox (_I know it may be the reason but please read my description carefully till the end_).

I tried two methods to connect to device:

![image](https://cloud.githubusercontent.com/assets/11060323/15799040/8759848e-2a4f-11e6-8eef-04bba0f0b6a0.png)

when using this method to connect to device:
```
void connectToDevice(android.app.Activity activity,
                     android.bluetooth.BluetoothDevice device  DefaultResponseHandler<android.bluetooth.BluetoothDevice,PPError<CardReaderManager.ChipAndPinConnectionStatus>> handler)
```
the automatic update is started and it fails with message like this:

`06-04 12:21:04.203 7749-8340/com.doddle.concession E/Volley: [16587] BasicNetwork.performRequest: Unexpected response code 500 for https://www.sandbox.paypal.com/webapps/hereapi/merchant/v1/cardReaderDevice/MIURA/M000/keys
06-04 12:21:04.206 7749-7749/com.doddle.concession E/PPHSDK: HereDeviceKeysRequest- RESPONSE BODY ON ERROR: {"correlationId":"c10716a49d238","errorCode":600000,"message":"MobileMerchantPaymentServ: Unknown Error Code: 506713","errorType":"service_error"}
06-04 12:21:04.206 7749-7749/com.doddle.concession D/PPHSDK: PPHSDK.MerchantManagerImpl-Active merchant is present.
06-04 12:21:04.207 7749-7749/com.doddle.concession D/PPHSDK: CalLoggingService-NEW MESSAGE: {"status":"-1","type":"BIZ","name":"Message.CLIENT","data":{"sessionId":"2623d764-2bf6-4314-b7cd-bd4502611656","timestamp":"2016-06-04 10:21:04:206 +0000","actionId":"Message","level":"ERROR","result":"-1","details":" : :  RESPONSE BODY ON ERROR: {\"correlationId\":\"c10716a49d238\",\"errorCode\":600000,\"message\":\"MobileMerchantPaymentServ: Unknown Error Code: 506713\",\"errorType\":\"service_error\"}"}}
06-04 12:21:04.225 7749-7749/com.doddle.concession E/PPHSDK: HereDeviceKeysRequest-Failure response from backend and contains errors. ErrorCode: 600000
06-04 12:21:04.225 7749-7749/com.doddle.concession D/PPHSDK: PPHSDK.MerchantManagerImpl-Active merchant is present.
06-04 12:21:04.225 7749-7749/com.doddle.concession D/PPHSDK: CalLoggingService-NEW MESSAGE: {"status":"-1","type":"BIZ","name":"Message.CLIENT","data":{"sessionId":"2623d764-2bf6-4314-b7cd-bd4502611656","timestamp":"2016-06-04 10:21:04:225 +0000","actionId":"Message","level":"ERROR","result":"-1","details":" : : Failure response from backend and contains errors. ErrorCode: 600000"}}
06-04 12:21:04.238 7749-7749/com.doddle.concession D/PPHSDK: CalLoggingService-NEW MESSAGE: {"status":"-1","type":"BIZ","name":"HereDeviceKeysRequest.CLIENT","data":{"sessionId":"2623d764-2bf6-4314-b7cd-bd4502611656","timestamp":"2016-06-04 10:21:04:237 +0000","actionId":"HereDeviceKeysRequest","level":"INFO","result":"-1","details":"{\"initialKSN\":\"FFFFFF027CC85F200000\",\"signedKeyLoadingCert\":\"-----BEGIN CERTIFICATE-----\\nMIID+zCCAuOgAwIBAgIJAMP6zD+Uum6fMA0GCSqGSIb3DQEBCwUAMIGLMQswCQYD\\nVQQGEwJHQjEYMBYGA1UECBMPQnVja2luZ2hhbXNoaXJlMRUwEwYDVQQHEwxTdG9r\\nZW5jaHVyY2gxGjAYBgNVBAoTEU1pdXJhIFN5c3RlbXMgTHRkMREwDwYDVQQLEwhU\\nZXJtaW5hbDEcMBoGA1UEAxMTMDEwLTQzMzA0Ny10ZXJtaW5hbDAeFw0xMDAxMDEw\\nMDAwMDBaFw0yOTEyMzEyMzU5NTlaMIGQMQswCQYDVQQGEwJHQjEYMBYGA1UECBMP\\nQnVja2luZ2hhbXNoaXJlMRUwEwYDVQQHEwxTdG9rZW5jaHVyY2gxGjAYBgNVBAoT\\nEU1pdXJhIFN5c3RlbXMgTHRkMREwDwYDVQQLEwhUZXJtaW5hbDEhMB8GA1UEAxMY\\nMDEwLTQzMzA0Ny1sb2NhbC1rZXlsb2FkMIIBIDANBgkqhkiG9w0BAQEFAAOCAQ0A\\nMIIBCAKCAQEAyPFrmulovm5tP8F0AVd+AmpKZMIm1w6m61vO26rDhy3VBJa8qixE\\nCL3rL6Zy8t5fyOvpW3hq6Nwd30aML8k5hLOYiCWE+7cDi9pu\\\/03aDDYZmILAaUj7\\nY9mxsnQbQ\\\/rgQXSU8uROCuhPDEh4ajr0fnurKW0G3Zz\\\/\\\/5O2uS0Lkh2vTd6+ZBFZ\\nstXuACSwufPocg+hSwCsvy7lJXE9ukExEq2SBvisCnF0dLbtFcK46NXQ8GpPOibN\\nBMzwPRrX\\\/\\\/0sFwXIV1dXg9pNC6fRLkWtfqEMTwt\\\/SigaQ0lVGFMnlRbzQsjA\\\/ApS\\n8IdXDIVReix7uNAVWqC25RyhKpWpryq1swIBA6NdMFswDAYDVR0TAQH\\\/BAIwADAL\\nBgNVHQ8EBAMCBSAwHQYDVR0OBBYEFEXGCsiVAlKiURNUqdw77uN2U53iMB8GA1Ud\\nIwQYMBaAFIzNa\\\/\\\/+dXTl3UCEjD8Ve3pCObtiMA0GCSqGSIb3DQEBCwUAA4IBAQBE\\n\\\/sQ2LSLOy5hvPkovJSrFtKv67t+iToU182Fg+3x8siAZ9cMWMuebXsGLBaO\\\/2mTV\\nk8vjO33K0mSC9SXCiWddMafekCtLBsumDTbYxDX+49fmsWkDjHQZyt\\\/tTWKUGzqz\\nDYmgRF66TDbU12zLv2Xm\\\/GzlfIZH0Pyt1A0sEbdtS\\\/CMGW5fX9WEKo90TahQCoc\\\/\\nvrrKWyXYzMBLbyLoVErKg8hTatnHofRq633pslrwEFs7U9RZZurkSCaMyPgtcJYe\\nLGuyhyxbusl29fScRstJ7gmA26bAvGcfsCOAxe\\\/fV+YWelFf1152WJkeejVz+m4O\\nlW2U1WEw2qIHWMmCnq0C\\n-----END CERTIFICATE-----\",\"signedTerminalCert\":\"-----BEGIN CERTIFICATE-----\\nMIIEGjCCAwKgAwIBAgIJAKs6t8tabBXOMA0GCSqGSIb3DQEBCwUAMIGmMQswCQYD\\nVQQGEwJHQjEYMBYGA1UECBMPQnVja2luZ2hhbXNoaXJlMRUwEwYDVQQHEwxTdG9r\\nZW5jaHVyY2gxGjAYBgNVBAoTEU1pdXJhIFN5c3RlbXMgTHRkMRMwEQYDVQQLEwpQ\\ncm9kdWN0aW9uMTUwMwYDVQQDFCxwcm9kLXNpZ24vZW1haWxBZGRyZXNzPWluZm9A\\nbWl1cmFzeXN0ZW1zLmNvbTAeFw0xMDAxMDEwMDAwMDBaFw0yOTEyMzEyMzU5NTla\\nMIGLMQswCQYDVQQGEwJHQjEYMBYGA1UECBMPQnVja2luZ2hhbXNoaXJlMRUwEwYD\\nVQQHEwxTdG9rZW5jaHVyY2gxGjAYBgNVBAoTEU1pdXJhIFN5c3RlbXMgTHRkMREw\\nDwYDVQQLEwhUZXJtaW5hbDEcMBoGA1UEAxMTMDEwLTQzMzA0Ny10ZXJtaW5hbDCC\\nASAwDQYJKoZIhvcNAQEBBQADggENADCCAQgCggEBAMNSL\\\/Bgf6c5UwQb4Od47qFr\\nlherDqrg2oQ4VjIYoKtRF+9PCpFum96tHtpuXa6wlSPUcQIkqNLlJfLFHV3MhHhQ\\npfq\\\/2XLdjI1cz1PP9q3d4XKh8qGFFS085vB0AsQyPfqnfxmaROAdrNm3QvXOFPH2\\nhOBZepTxwXLgOTfo9sFx8Y9bFsoi+Si\\\/S6no6Bha766FGUBxFacv3YiBrp5lsfZL\\n9xX1ErUHkJNJddH44KgDQpIuazJo56nlFFpFLe9fmXnGblxlV4WCil7KiIqZ9Pi3\\nZaH6y\\\/a8SN07sUBFO0oYHDUZmGh3gI1oYimdmMo1oAQZKI9Bq7j\\\/Ta0jBv3+mSEC\\nAQOjZjBkMBIGA1UdEwEB\\\/wQIMAYBAf8CAQAwDgYDVR0PAQH\\\/BAQDAgEGMB0GA1Ud\\nDgQWBBSMzWv\\\/\\\/nV05d1AhIw\\\/FXt6Qjm7YjAfBgNVHSMEGDAWgBSbzDFsr\\\/ZgrpCM\\nXVd5NrYvcwoFvDANBgkqhkiG9w0BAQsFAAOCAQEAHC1IZizkGDmLqTmbDC3jjKxe\\nP6t84J+qdjFMp04YC+ohts5wgmHbFbcwdqrriQjpr7yoq\\\/rURD6abP90NpqDeb3A\\n5bmA40MwfbtBqN5xHXztkVUCgD2eb4xLIKGVz\\\/B2qYq3SFgfki9l+HjJiBagyR4I\\nttyYbcxS7MOMdDd\\\/v7FkvmaXpvwy4GntvshRE+\\\/91pPnZh64cymvt46xMoxvJNJP\\nn018VbIy2vvMDgdKiSCxdkxRzq6ooJIGpWSKPWtAeDXNRRk9ZCXaMrOAkqbQnoku\\nAkI146otvERygquJUUU55cw3zJT7gEfeJPB06+dNcPkga9YtgJB4a9ESLeHXIg==\\n-----END CERTIFICATE-----\",\"signedProductSigningCert\":\"-----BEGIN CERTIFICATE-----\\nMIIEMjCCAxqgAwIBAgIJAKQmBPwuy8TAMA0GCSqGSIb3DQEBCwUAMIGkMQswCQYD\\nVQQGEwJHQjEYMBYGA1UECBMPQnVja2luZ2hhbXNoaXJlMRUwEwYDVQQHEwxTdG9r\\nZW5jaHVyY2gxGjAYBgNVBAoTEU1pdXJhIFN5c3RlbXMgTHRkMRMwEQYDVQQLEwpQ\\ncm9kdWN0aW9uMTMwMQYDVQQDFCpNaXVyYUNBL2VtYWlsQWRkcmVzcz1pbmZvQG1p\\ndXJhc3lzdGVtcy5jb20wHhcNMTAwMTAxMDAwMDAwWhcNMjkxMjMxMjM1OTU5WjCB\\npjELMAkGA1UEBhMCR0IxGDAWBgNVBAgTD0J1Y2tpbmdoYW1zaGlyZTEVMBMGA1UE\\nBxMMU3Rva2VuY2h1cmNoMRowGAYDVQQKExFNaXVyYSBTeXN0ZW1zIEx0ZDETMBEG\\nA1UECxMKUHJvZHVjdGlvbjE1MDMGA1UEAxQscHJvZC1zaWduL2
06-04 12:21:04.250 7749-7749/com.doddle.concession D/PPHSDK: CalLoggingService-NEW MESSAGE: {"status":"-1.600000","type":"BIZ","name":"HereDeviceKeysRequest.CLIENT","data":{"sessionId":"2623d764-2bf6-4314-b7cd-bd4502611656","timestamp":"2016-06-04 10:21:04:249 +0000","actionId":"HereDeviceKeysRequest","level":"ERROR","result":"-1","correlationId":"c10716a49d238","duration":1784}}
06-04 12:21:04.278 7749-7749/com.doddle.concession D/PPHSDK: CardReaderServiceImpl-HereDeviceKeysRequest response failure
06-04 12:21:04.278 7749-7749/com.doddle.concession D/PPHSDK: PPHSDK.MerchantManagerImpl-Active merchant is present.
06-04 12:21:04.279 7749-7749/com.doddle.concession D/PPHSDK: CalLoggingService-NEW MESSAGE: {"status":"0","type":"BIZ","name":"Message.CLIENT","data":{"sessionId":"2623d764-2bf6-4314-b7cd-bd4502611656","timestamp":"2016-06-04 10:21:04:278 +0000","actionId":"Message","level":"INFO","result":"0","details":"SoftwareUpdate:  : invoke of exchangeEncryptionKeys. response: null"}}
06-04 12:21:04.293 7749-7749/com.doddle.concession D/PPHSDK: SoftwareUpdate:  : invoke of exchangeEncryptionKeys. response: null
06-04 12:21:04.293 7749-7749/com.doddle.concession D/PPHSDK: PPHSDK.MerchantManagerImpl-Active merchant is present.
06-04 12:21:04.294 7749-7749/com.doddle.concession D/PPHSDK: CalLoggingService-NEW MESSAGE: {"status":"-1","type":"BIZ","name":"Message.CLIENT","data":{"sessionId":"2623d764-2bf6-4314-b7cd-bd4502611656","timestamp":"2016-06-04 10:21:04:294 +0000","actionId":"Message","level":"ERROR","result":"-1","details":"SoftwareUpdate:  : invoke of exchangeEncryptionKeys failed. Calling resetUpdater and failing update process"}}
06-04 12:21:04.304 7749-7749/com.doddle.concession E/PPHSDK: SoftwareUpdate:  : invoke of exchangeEncryptionKeys failed. Calling resetUpdater and failing update process
06-04 12:21:04.304 7749-7749/com.doddle.concession D/PPHSDK: PPHSDK.MerchantManagerImpl-Active merchant is present.
06-04 12:21:04.304 7749-7749/com.doddle.concession D/PPHSDK: CalLoggingService-NEW MESSAGE: {"status":"-1","type":"BIZ","name":"Message.CLIENT","data":{"sessionId":"2623d764-2bf6-4314-b7cd-bd4502611656","timestamp":"2016-06-04 10:21:04:304 +0000","actionId":"Message","level":"ERROR","result":"-1","details":"SoftwareUpdate:  : onUpdate Failed notifying the listener that update has been failed"}}
06-04 12:21:04.315 7749-7749/com.doddle.concession E/PPHSDK: SoftwareUpdate:  : onUpdate Failed notifying the listener that update has been failed
06-04 12:21:04.315 7749-7749/com.doddle.concession E/PPHSDK: CardReaderManagerImpl SW_UPDATE-onInstallFailed!!!
06-04 12:21:04.315 7749-7749/com.doddle.concession D/PPHSDK: PPHSDK.MerchantManagerImpl-Active merchant is present.
`

When I use this method to connect to device:
`void connectToDevice(android.bluetooth.BluetoothDevice device,
                     ChipAndPinStatusUpdateHandler<CardReaderManager.ChipAndPinStatusResponse,PPError<CardReaderManager.ChipAndPinConnectionStatus>> handler)`

I'm getting into onCompleted method where `CardReaderManager.ChipAndPinStatusResponse response`  is null and `PPError<CardReaderManager.ChipAndPinConnectionStatus> error` gives such data:
_**Interesting thing: when using this method there's no automatic update**._

```
       D/PayPalHereSDKWrapper: connectDevice Response Handler: **onInitiated**
       D/PayPalHereSDKWrapper: errorMsg null
       D/PayPalHereSDKWrapper: errorDevMsg null
       D/PayPalHereSDKWrapper: errorCode ConnectionInProgress
       D/PayPalHereSDKWrapper: detailerErrorCode null

       D/PayPalHereSDKWrapper: connectDevice Response Handler: **onStatusUpdated**
       D/PayPalHereSDKWrapper: errorMsg null
       D/PayPalHereSDKWrapper: errorDevMsg null
       D/PayPalHereSDKWrapper: errorCode TerminalInfoAvailable
       D/PayPalHereSDKWrapper: detailerErrorCode null

       D/PayPalHereSDKWrapper: connectDevice Response Handler: **onStatusUpdated**
       D/PayPalHereSDKWrapper: errorMsg null
       D/PayPalHereSDKWrapper: errorDevMsg null
       D/PayPalHereSDKWrapper: errorCode ConnectedAndConfiguring
       D/PayPalHereSDKWrapper: detailerErrorCode null

       D/PayPalHereSDKWrapper: connectDevice Response Handler: **onCompleted**
       D/PayPalHereSDKWrapper: errorMsg 0
       D/PayPalHereSDKWrapper: errorDevMsg null
       D/PayPalHereSDKWrapper: errorCode **ErrorSoftwareUpdateRequired**
       D/PayPalHereSDKWrapper: detailerErrorCode null


```

**Questions:**
1. Is is possible to update CardReader online without using official PayPal Here App and Live account?
I would like to be able to plug the device to my pc and install update on it.
2. Is the **Card Reader software update ** update the main reason of blocking me to connect to reader from app?

**Comment by ppmtscory** [comment]
Yes, the reader update is what's blocking you.  Currently the EMV reader does not work in the Sandbox environment so you'll need to utilize the Live environment for any updates and testing with the EMV reader.  This update can be done via the PayPal Here App or via the SDK, either way, but has to be in the Live environment.

**Comment by ppmtscory** [comment]
Yes, the reader update is what's blocking you.  Currently the EMV reader does not work in the Sandbox environment so you'll need to utilize the Live environment for any updates and testing with the EMV reader.  This update can be done via the PayPal Here App or via the SDK, either way, but has to be in the Live environment.

**Comment by mastahnish** [comment]
Thank you @ppmtscory that was correct. 
I faced another issue #71 when trying to perform transaction using SampleApp and PayPalHere CardReader. Maybe you could take a look on it as well. 

Thank you for your help so far!

**Comment by ppmtscory** [comment]
You're welcome.  I will close this issue and take a look at your other one.
