### ISSUE TITLE
Are Google Play Services mandatory when using PayPalHereSDK?

### ISSUE THREAD

**Issue by mastahnish** [PayPal-Mobile/android-here-sdk-dist#70]
Hello, 

I want to integrate PayPalHere device with Zebra MC40 device, which doesn't support Google Play Services.

With such setup - will it be possible to perform payment transactions using PayPalHere device (card reader)?

**Comment by ppmtscory** [comment]
The SDK is compiled against Google Play services so if the phone is not able to utilize that, then unfortunately, it's most likely not supported.
