### ISSUE TITLE
[Release 1.6.2.6] NPE at HereInvoiceCreateRequest.java:84

### ISSUE THREAD

**Issue by brooth** [PayPal-Mobile/android-here-sdk-dist#74]
After each successful sandbox payment SDK fails with:

```
 java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.paypal.merchant.sdk.domain.Address.getLine1()' on a null object reference
       at com.paypal.merchant.sdk.internal.service.impl.hereapi.HereInvoiceCreateRequest.getPayloadAsString(HereInvoiceCreateRequest.java:84)
       at com.paypal.merchant.sdk.internal.service.impl.hereapi.HereInvoiceUpdateRequest.getPayloadAsString(HereInvoiceUpdateRequest.java:62)
       at com.paypal.merchant.sdk.internal.service.ServiceInterfaceVolleyImpl.submit(ServiceInterfaceVolleyImpl.java:209)
       at com.paypal.merchant.sdk.internal.service.InvoiceServiceImpl.updateInvoice(InvoiceServiceImpl.java:205)
       at com.paypal.merchant.sdk.internal.TransactionManagerImpl.processPaymentWithBackend(TransactionManagerImpl.java:950)
       at com.paypal.merchant.sdk.internal.TransactionManagerImpl.moveStateToProcessingPayment(TransactionManagerImpl.java:725)
       at com.paypal.merchant.sdk.internal.TransactionManagerImpl.processPayment(TransactionManagerImpl.java:690)
       at com.paypal.merchant.sdk.internal.ui.SDKUITransactionController.processPaymentInternal(SDKUITransactionController.java:223)
       at com.paypal.merchant.sdk.internal.ui.SDKUITransactionController.processPayment(SDKUITransactionController.java:217)
       at com.paypal.merchant.sdk.internal.ui.emv.EMVUITransactionController.processPayment(EMVUITransactionController.java:291)
       at com.paypal.merchant.sdk.internal.ui.emv.EMVUITransactionController.onSuccessfulCardRead(EMVUITransactionController.java:965)
       at com.paypal.merchant.sdk.internal.ui.emv.EMVUITransactionController$19.onSuccessfulCardRead(EMVUITransactionController.java:933)
       at com.paypal.merchant.sdk.internal.CardReaderEventSession.onCardReadSuccess(CardReaderEventSession.java:35)
       at com.paypal.merchant.sdk.internal.CardReaderManagerImpl$CardReadSuccessMessage.run(CardReaderManagerImpl.java:1111)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by brooth** [comment]
BTW, my live merchant account has an address. But there is no address field for sandbox accounts on https://developer.paypal.com/developer/accounts/create.

**Comment by ppmtscory** [comment]
If everything is set up with the merchant initially, then the SDK will grab the address information from the account.  Did you send your merchant account through the onboarding process to grant permissions to your Partner account to process on it's behalf?

**Comment by ppmtscory** [comment]
If everything is set up with the merchant initially, then the SDK will grab the address information from the account.  Did you send your merchant account through the onboarding process to grant permissions to your Partner account to process on it's behalf?  Is your sandbox merchant account enabled for PayPal Here?

**Comment by brooth** [comment]
>  Did you send your merchant account through the onboarding process to grant permissions to your Partner account to process on it's behalf?
No, I need to escape this. I obtained the token through https://api.sandbox.paypal.com/v1/oauth2/token (via curl). I am trying to integrate PPHere in our taxi solution software, so we're going to create one marchant account per our customer and sub-account (like these https://developer.paypal.com/developer/accounts/create) for each taxi driver. Also, we need to obtain the tokens via our backend, i.e. Android app requests our server for the token passing driver ID and the server matches this driver with paypal sub-account, authorizes it and returns the needed information (inc. token). Obviously, in this case we can't use your web page to grand the access. Please, guide me to the tutorial, explaining how I can achieve that.

**Comment by ppmtscory** [comment]
You'll have to do the onboarding a single time so that you can grant access and get the refresh token to store and use later on.  Even if this is for your own account, it still has to be done.  You'll need to go through the onboarding to grant permissions, store the refresh token you get, and then use that refresh token later on to generate the access token when needed.  More info on this process can be found in the Merchant Onboarding guide located in the docs folder of this repo.

**Comment by brooth** [comment]
Thank you for the information. I have done onboarding process and given permissions to my application. Moreover, now I get valid access token and pass authentication. However, I still get the null pointer exception I posted above when trying to perform a transaction. Please let me know if you need more information.

**Comment by ppmtscory** [comment]
I'm guessing that your Sandbox merchant account is not enabled for PayPal Here.  Can you let me know the sandbox account and I can take a look?

**Comment by brooth** [comment]
Sure, it has client ID: AYAoBEy1RISsWORgRshrP5suI_50FBAU5k6vOnRHI6WyvZOATnyxK3z2LgAHZvqruheUvhmw9z5aM5fC
and here is a screenshot with enabled 'PP Here' setting https://gyazo.com/ad7de401812c29d4f28696f106da9181

**Comment by ppmtscory** [comment]
Those are you App settings, but I need to know the sandbox email address that you logged into and went through the onboarding with.

**Comment by brooth** [comment]
I went though the onbording process with ar@haulmont.com but I get the token with ar-facilitator@haulmont.com credentials since I can't find sandbox Client ID
 and Secret code for ar@haulmont.com

**Comment by ppmtscory** [comment]
That wouldn't work because your non-facilitator account is NOT a sandbox account.  You'll want to go through the onboarding process with the -facilitator account and also use that accounts credentials to turn the auth code into a refresh and access token.  Also, make sure all your endpoints are pointing to the sandbox environment.  Your facilitator account is enabled for PPH so using that account to go through the onboarding process should work just fine.

**Comment by brooth** [comment]
After all I can't get it work. First of all I tried to follow [this guide] (https://developer.paypal.com/docs/integration/paypal-here/sandbox-testing/getting-paypal-here-approval-for-sandbox-accounts/) from scratch and created "Rayn" sandbox acc. When I go through the onboarding process via this [uri](https://www.sandbox.paypal.com/webapps/mobilemerchant/page/mpa/ob/geturl?onbver=2.0&country.x=US&partnertype=sdk&swiper=n&returnurl=https://www.example.com) and enter Rayn's credentials it redirects me on [this page](https://gyazo.com/4b6978fe5aa337ea8c4fcb2f926536f2) so I'm not allowed to "Agree and Continue" as it described in the guide. And yes, I tried to replace "www.example.com" with my own endpoint (accessible outside) but no affect (no requests to my endpoint)

Secondly, I used xxxxx-facilitator@haulmont.com (from my previous comment) within your sample app and it works just fine. I did a payment and even refunded it. But when I receive the token for this acc via `curl -v https://api.sandbox.paypal.com/v1/oauth2/token \\n  -H "Accept: application/json" \\n  -H "Accept-Language: en_US" \\n  -u "<Client ID>:<Secret>:" \\n  -d "grant_type=client_credentials"` after each payment the SDK fails with the NPE

So guys, please, please help me here. I need a step-by-step tutorial how to
1. create sandbox acc allowed to login to PPHere  SDK and receive payments
2. how to grad all the accesses to this acc if needed
3. how to receive access/refresh tokens via `curl` so I can just pass this token in this code:

        Credentials creds = new OAuthCredentials("TOKEN");
        PayPalHereSDK.setCredentials(creds, setCredentialsHandler);

Many thanks!

**Comment by ppmtscory** [comment]
@brooth going through the sample app works because you're generating a third party access token.  When you use your facilitator account with that curl call, that's a first party token, which can't be used within the SDK.  Do the following with your facilitator account....

1. Direct to the following link - using YOUR client ID (from your facilitator account) and `redirect_uri` that's set in your REST App.
```
https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize?scope=openid address email https://uri.paypal.com/services/paypalattributes/business https://uri.paypal.com/services/paypalhere&response_type=code&redirect_uri=<your redirect url>&client_id=<your client id>
```

2. On that page, login with your facilitator account email/pwd.  Once done, you'll be directed back to your `redirect_uri` with the authorization code attached to the query string.

3. On your `redirect_uri`, you'll need the following curl command to turn the authorization code into a refresh/access tokens.  Use a standard base64 encoded version of your facilitator account client ID, colon (:), and client secret.
```
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Authorization: Basic <base64 encoded_clientid:secret>" -H "Cache-Control: no-cache" -d 'grant_type=authorization_code&code=<auth_code>' "https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/tokenservice"
```

4. The result of that curl command should contain a refresh and access token.  This access token will be a third party access token and can then be passed into the SDK using the `OAuthCredentials` method you mentioned above.  You'll want to save the refresh token because you'll use that to generate a new access token when the current one expires (8 hr expiry).

**Comment by brooth** [comment]
No luck again. 

> Direct to the following link - using YOUR client ID
What do you mean by YOUR client ID? where can I get it? The only client id I have is the one in my app. 

So, I am on `developer.paypal.com`. Under "Dashboard" - "My Apps & Credentials" - "REST API apps" I create an app "my-app". As a "Sandbox developer account" I selected "xxx-facilitator@haulmont.com". Now I have a "Client ID" and a "Secret" under "SANDBOX API CREDENTIALS". I also checked "PayPal Here" under "SANDBOX APP SETTINGS".

Next, I use the link you provided and replace the params:

	https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize?scope=openid address email https://uri.paypal.com/services/paypalattributes/business https://uri.paypal.com/services/paypalhere&response_type=code&redirect_uri=http://127.0.0.1:8000&client_id=<CLIENT ID FROM MY-APP>

It responses with an error:
>Relying Party Validation error: redirect_uri provided in the request does not match with the registered redirect_uri. Please check the request.

Ok, I go back to the dev console and enter "http://127.0.0.1:8000" under "Dashboard" - "My Apps & Credentials" - "my-app" - "SANDBOX APP SETTINGS" - "Return URL".

Try again with the same link and next error is:
>Relying Party Validation error: scope in the request does not match any of the registered clients. Please check the request.

After playing around I deleted "address email" from the link so it's:

	https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize?scope=openid https://uri.paypal.com/services/paypalattributes/business https://uri.paypal.com/services/paypalhere&response_type=code&redirect_uri=http://127.0.0.1:8000&client_id=<CLIENT ID FROM MY-APP>

Now no errors and it opens a "Use your PayPal account to log in to my-app" page so I enter "xxx-facilitator@haulmont.com" as email and its password. Another page and I click "Agree". It redirects me on my local server so I can copy the code.

I use your `curl` command with the code and the creds:
	
	curl -X POST -u "<MY-APP CLIENT ID>:<MY-APP SECRET>" -H "Content-Type: application/x-www-form-urlencoded" -H "Cache-Control: no-cache" -d 'grant_type=authorization_code&code=<CODE FROM REDIRECT_URI> ' "https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/tokenservice"

The response:

	{"token_type":"Bearer","expires_in":"28800","refresh_token":"<TOKEN>","id_token":"<TOKEN>","access_token":"<TOKEN>"}


Now I pass access token in:

    Credentials creds = new OAuthCredentials("<access_token>");
    PayPalHereSDK.setCredentials(creds, setCredentialsHandler);

And the SKD fails again with absolutely the same NPE!

I also tried this uri (found example in the docs) to recieve the code but the error still the same:

	https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize?scope=https://uri.paypal.com/services/paypalhere&response_type=code&redirect_uri=http://127.0.0.1:8000&client_id=<CLIENT ID FROM MY-APP>

Any help?

**Comment by ppmtscory** [comment]
Yes - you'll get the same NPE because you deleted the necessary scopes (address, email).  You'll need to go into your App on dev portal and select those options underneath the Log In With PayPal section so that you can add them back to your code.  All the scopes in my example are required.  For simplicity sake, since it's sandbox, just check all the boxes underneath the Log In With PayPal section so that you have everything selected.  Once you do that, run through the scenario again and you shouldn't see the scope error.

**Comment by brooth** [comment]
Finally it works! Thank you!

**Comment by alwynlombaard** [comment]
I have exactly the same experience, decrypting the documentation and the sample server is an absolute nightmare. It is one of the worst SDK integration experiences I've had.  Hopefully this will save me :)
