### ISSUE TITLE
 Cannot proceed with this merchant account. ineligible

### ISSUE THREAD

**Issue by brooth** [PayPal-Mobile/android-here-sdk-dist#78]
2 days ago [I finally configured my sandbox account](https://github.com/PayPal-Mobile/android-here-sdk-dist/issues/74) to work with the SDK, but today it stopped working without any modifications.

        Credentials creds = new OAuthCredentials(token);
        PayPalHereSDK.setCredentials(creds, setCredentialsHandler);

now returns 

        error: Cannot proceed with this merchant account. ineligible, code: InvalidMerchant

what exactly became ineligible?

**Comment by ppmtscory** [comment]
@brooth what are you seeing in logcat?  Is there mention of a missing business name?

**Comment by brooth** [comment]
@ppmtscory 
nothing unusual

	V: not Base app: Adding window Window{18382f93 u0 Paypal HERE} at 8 of 14
	W: couldn't log to binary event log: overflow.
	setCredentialsHandler.onError(error: Cannot proceed with this merchant account. ineligible, code: InvalidMerchant)

last line from my logger: 

        DefaultResponseHandler.onError(PPError<MerchantManager.MerchantErrors> error) {
             logger.w("setCredentialsHandler.onError(error: %s, code: %s)",
                            error.getDetailedMessage(), String.valueOf(error.getErrorCode()));
        }

**Comment by ppmtscory** [comment]
Since this is just sandbox, what's the access token you are using?

**Comment by brooth** [comment]
A103.RqFC_pf1uZqWPEoyXsQVyEDxCfwaN7JvxQ8e7kgPLDsngtXVwIO_CesdALrzT-tf.QPAMsbNTG003DtrIZgftiVPnc4q

**Comment by ppmtscory** [comment]
Crap, ok.  There's currently an issue right now with our token services where access tokens starting with A103, while valid, are not containing the permission to grab the business name from the account.  This will hopefully be fixed tonight.  However, in the meantime, there's 2 ways around it.

1. A safeguard against this would be to populate the business name manually.  When you get the success callback from setting credentials, you can add the business name to the invoice to ensure it's there.  `merchant.setBusinessName("Corndog Palace");`
2. You can regenerate the access token until you get one that starts with A015.  These tokens contain the right permissions to gather the business name.  The difference in tokens is simply the route it takes internally in our system when being generated.  

Again, this should be fixed tonight but you can do the above steps to correct it now.  I'd recommend adding the business name manually, anyway, just so you ensure it's set every time.  This way, if there was something happened later on with the flow and you somehow initiate payment activities prior to the merchant being fully initialized, you'll be covered.

**Comment by brooth** [comment]
Ok, thanks!

**Comment by brooth** [comment]
Still doesn't work

**Comment by ppmtscory** [comment]
There should be no issues with business name with either token type now.  The fix was pushed out Friday evening and I've tested everything this morning with all being successful.

**Comment by brooth** [comment]
I've tried everything and I can't get it work. I've recreated rest app,  got through the onboarding process, created new tokens  but the SDK still returning "error: Cannot proceed with this merchant account. ineligible, code: InvalidMerchant". Here is my last valid token "A103.vcj__VUznZD_c4c9cf1GZ-LXYCx82VHfYOzRE9-QwUjIGYSVJmqbV25BCrW1PT6E.C5XuHH9KEMuEPT2BivDOm6PgT2K". Please, check what's wrong with it

**Comment by ppmtscory** [comment]
@brooth I'm fairly certain there's a larger issue happening in the Sandbox right now as I'm seeing some troubles with my account as well.  I'm looking into it and will update you once I know more.

**Comment by brooth** [comment]
@ppmtscory 
May be this can help. I've tried to login within your sample app and here is the logcat output:
```
D: com.paypal.merchant.sdk.internal.service.SDKServiceImpl$FeatureMapRequest- Response Body: 
   {
       "VERSION": "1.1",
       "GLOBAL": {
           "sig": false,
           "apic": true,
           "nslall": false,
           "fhlem": [],
           "fhlbid": [],
           "SWU_CHECK_PERIOD": 300,
           "READER_SLEEP_DELAY": 60
       },
       "ANDROID": {
           "minSDKVersion": "1.0"
       },
       "IOS": {
           "minSDKVersion": "1.0"
       },
       "US": {
           "MCC_CODES": {
               "4121": "*",
               "5812": "*",
               "5813": "*",
               "5814": "*",
               "7230": "*",
               "7298": "*",
               "4411": "*",
               "7519": "*",
               "7011": "*",
               "7512": "*"
           },
           "CONTACTLESS_LIMIT": "10000"
       },
       "GB": {
           "CONTACTLESS_LIMIT": "30"
       },
       "AU": {
           "CONTACTLESS_LIMIT": "*"
       }
   }
D: MerchantStatusRequest- Response Body: 
   {
       "status": "ineligible",
       "categoryCode": "5533",
       "businessCategoryExists": true
   }
```

**Comment by ppmtscory** [comment]
The service, internally here, is not behaving correctly so it's showing that PayPal Here isn't enabled on the account.  I've already escalated to the team and am just awaiting resolution.  If you wanted, or are able, you can test in Production and refund the payment as this is only affecting Sandbox.

**Comment by ppmtscory** [comment]
@brooth my apologies for the delay but this has been resolved.  You should be good to go now.

**Comment by brooth** [comment]
It does work. Thanks!
