### ISSUE TITLE
500 Internal server error when trying to obtain an access token

### ISSUE THREAD

**Issue by alwynlombaard** [PayPal-Mobile/android-here-sdk-dist#89]
This worked on Friday but now this is happening for the same refresh token. 

May I just add a note that this SDK integration is just outright a bad experience and the Sandbox behaviour is totally unreliable. Further it is unclear where and how to raise issues with the Sandbox. This has been a very frustrating product integration so far.

When I try to get an access token here:  

    https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/tokenservice

I get the following response:

    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html><head> 
    <title>500 Internal Server Error</title>
    </head><body>
    <h1>Internal Server Error</h1>
    <p>The server encountered an internal error or
    misconfiguration and was unable to complete
    your request.</p>
    <p>Please contact the server administrator,
     webmaster@paypal.com and inform them of the time the error occurred,
    and anything you might have done that may have
    caused the error.</p>
    <p>More information about this error may be available
    in the server error log.</p>
    </body></html>

**Comment by ppmtscory** [comment]
There seems to be an issue in the sandbox right now for this endpoint.  We're currently looking into it and I will update you once we know more.

**Comment by ppmtscory** [comment]
This has been resolved now.
