### ISSUE TITLE
Sample app for Android is not working for Live

### ISSUE THREAD

**Issue by chauhanmahesh** [PayPal-Mobile/android-here-sdk-dist#90]
Do I have to make any changes in the sample app to make it work for Live environment. When choosing Live and tapping on Login, it always showing this page
"Relying party validation error: client_ID or redirect_URL provided in the request does not match any of the registered clients. Please check the request and try again."

**Comment by ppmtscory** [comment]
Ah... I'm seeing the same.  I'll get the folks with access to the sample server to fix this for us.  Standby...

**Comment by ppmtscory** [comment]
@chauhanmahesh this should be resolved now.  I'm able to get the login without error when setting the sample app to Live.

**Comment by chauhanmahesh** [comment]
Thanks @ppmtscory.
